name: Snyk Setup
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
    - name: Snyk monitor 
      run: snyk test
      env:
        SNYK_TOKEN: ${{ secrets.3d6983e2-99cc-4a8b-84b2-cd2ef36431b3 }}